#!/usr/bin/env node
/**
 * GitHub Repository Sync Script
 *
 * This script runs nightly via GitHub Actions to sync repository data.
 * It fetches all repos (public + private) and extracts portfolio documentation.
 *
 * Output files (in public/data/):
 * - private_repos.json: All repos with enriched metadata
 * - featured_repos.json: Curated list of featured projects
 * - portfolio/[repo-name]/: Markdown docs (architecture.md, stack.md, qa.md)
 *
 * Requirements:
 * - GH_PRIVATE_TOKEN env var with repo access
 *
 * Usage:
 *   node scripts/fetch_private_repos.js
 *   # Or via GitHub Actions: .github/workflows/sync-private-repos.yml
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_DIR = path.join(__dirname, '..', 'public', 'data');
const PRIVATE_REPOS_PATH = path.join(OUTPUT_DIR, 'private_repos.json');
const FEATURED_REPOS_PATH = path.join(OUTPUT_DIR, 'featured_repos.json');
const PORTFOLIO_DIR = path.join(OUTPUT_DIR, 'portfolio');
const SCREENSHOTS_DIR = path.join(__dirname, '..', 'public', 'screenshots');
const GITHUB_API = 'https://api.github.com';
const TOKEN = process.env.GH_PRIVATE_TOKEN;

// Portfolio files to fetch from each repo's .portfolio/ directory
const PORTFOLIO_FILES = ['architecture.md', 'stack.md', 'qa.md'];

// Preview images to fetch from each repo's .portfolio/ directory
const PREVIEW_FILES = ['preview.png', 'preview.gif'];

// List of repo names that should be featured (order matters for display)
const FEATURED_REPO_NAMES = [
  'Private-Collab-Whiteboard',
  'BTC-Explorer',
  'Git-Archiver-Web',
  'AHSR-senior-design-archive',
  'RepoLens',
  'Blackjack-Trainer'
];

// Manual entries for external repos not in the user's GitHub account.
// All projects now live as real GitHub repos under Technical-1, so this is
// empty. Keep the array (and the loop that consumes it) in case a future
// project needs a manual entry again.
const MANUAL_REPOS = [];

// Per-repo overrides keyed by `full_name`. Merged onto the auto-fetched
// data in processRepo(). Useful when GitHub's reported language stats
// misrepresent the work, or to attach metadata GitHub doesn't track
// (role, duration, etc.).
const REPO_OVERRIDES = {
  'Technical-1/AHSR-senior-design-archive': {
    // Language breakdown derived from `cloc` on the 15 team-written sub-repos
    // (excluding 6 upstream forks: ros2_control*, OrbbecSDK_ROS2, ros2_explorer,
    // rplidar_ros2). The 324k XML lines (Gazebo worlds, URDFs) are folded into
    // Python since they were generated by team Python tooling.
    // Sum: 631,694 lines, matching the cloc consolidated total.
    languages: ['Python', 'JSON', 'YAML', 'C', 'Text', 'CMake', 'C++', 'Shell', 'Makefile', 'PowerShell', 'Markdown'],
    language_bytes: {
      Python: 348913,    // 24,885 native Python + 324,028 XML generated by Python tooling
      JSON: 218973,
      YAML: 14449,
      C: 11319,
      Text: 10099,
      CMake: 9974,
      'C++': 8461,
      Shell: 3797,
      Makefile: 2123,
      PowerShell: 1648,
      Markdown: 1128
    },
    primary_language: 'Python',
    metadata: {
      role: 'Software Lead',
      duration: 'Jan 2023 - Dec 2024'
    }
  }
};

if (!TOKEN) {
  console.error('Missing GH_PRIVATE_TOKEN env var. Set it in the workflow/repo secrets.');
  process.exit(1);
}

const headers = {
  'Authorization': `token ${TOKEN}`,
  'User-Agent': 'private-repo-sync',
  'Accept': 'application/vnd.github+json'
};

async function fetchJson(url) {
  const res = await fetch(url, { headers });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Request failed ${res.status} ${res.statusText}: ${text}`);
  }
  return res.json();
}

async function fetchFileContent(owner, repo, filePath) {
  const url = `${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`;
  try {
    const res = await fetch(url, { headers });
    if (!res.ok) {
      if (res.status === 404) return null; // File doesn't exist
      return null;
    }
    const data = await res.json();
    if (data.content && data.encoding === 'base64') {
      return Buffer.from(data.content, 'base64').toString('utf8');
    }
    return null;
  } catch (err) {
    return null;
  }
}

async function fetchBinaryFile(owner, repo, filePath) {
  const url = `${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`;
  try {
    const res = await fetch(url, { headers });
    if (!res.ok) {
      if (res.status === 404) return null; // File doesn't exist
      return null;
    }
    const data = await res.json();

    // For small files, content is returned as base64
    if (data.content && data.encoding === 'base64') {
      return Buffer.from(data.content, 'base64');
    }

    // For large files (>1MB), GitHub doesn't include content
    // Use the download_url instead (requires auth for private repos)
    if (data.download_url) {
      const rawRes = await fetch(data.download_url, { headers });
      if (!rawRes.ok) return null;
      const arrayBuffer = await rawRes.arrayBuffer();
      return Buffer.from(arrayBuffer);
    }

    return null;
  } catch (err) {
    console.error(`  Error fetching ${filePath}: ${err.message}`);
    return null;
  }
}

async function fetchPortfolioFiles(repo) {
  const [owner, repoName] = repo.full_name.split('/');
  const portfolioData = {};

  for (const fileName of PORTFOLIO_FILES) {
    const content = await fetchFileContent(owner, repoName, `.portfolio/${fileName}`);
    if (content) {
      portfolioData[fileName] = content;
    }
  }

  return Object.keys(portfolioData).length > 0 ? portfolioData : null;
}

async function savePortfolioFiles(repoName, portfolioData) {
  if (!portfolioData) return;

  const repoDir = path.join(PORTFOLIO_DIR, repoName);
  fs.mkdirSync(repoDir, { recursive: true });

  for (const [fileName, content] of Object.entries(portfolioData)) {
    const filePath = path.join(repoDir, fileName);
    fs.writeFileSync(filePath, content, 'utf8');
  }

  console.log(`  Saved portfolio files for ${repoName}`);
}

function getRepoSlug(repoName) {
  return repoName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

async function fetchAndSavePreviewImages(repo) {
  const [owner, repoName] = repo.full_name.split('/');
  const slug = getRepoSlug(repo.name);
  const screenshotDir = path.join(SCREENSHOTS_DIR, slug);
  const savedPaths = [];

  for (const fileName of PREVIEW_FILES) {
    const content = await fetchBinaryFile(owner, repoName, `.portfolio/${fileName}`);
    if (content) {
      fs.mkdirSync(screenshotDir, { recursive: true });
      const filePath = path.join(screenshotDir, fileName);
      fs.writeFileSync(filePath, content);
      savedPaths.push(`/screenshots/${slug}/${fileName}`);
      console.log(`  Saved preview image: ${fileName}`);
    }
  }

  return savedPaths;
}

async function fetchAllRepos(visibility) {
  let page = 1;
  const perPage = 100;
  const repos = [];

  while (true) {
    const url = `${GITHUB_API}/user/repos?visibility=${visibility}&per_page=${perPage}&page=${page}&affiliation=owner`;
    const batch = await fetchJson(url);
    repos.push(...batch);
    if (batch.length < perPage) break;
    page += 1;
  }

  // Repos to exclude from the site (sensitive content)
  const EXCLUDED_REPOS = ['SAA'];

  // Keep only active, non-fork repos, excluding sensitive ones
  return repos.filter(r => !r.fork && !r.archived && !EXCLUDED_REPOS.includes(r.name));
}

async function fetchLanguagesForRepo(repo) {
  try {
    const langData = await fetchJson(repo.languages_url);
    return langData;
  } catch (err) {
    console.error(`Failed to fetch languages for ${repo.full_name}: ${err.message}`);
    return {};
  }
}

function computePrimaryLanguage(langBytes) {
  const entries = Object.entries(langBytes || {});
  if (!entries.length) return null;
  entries.sort((a, b) => b[1] - a[1]);
  return entries[0][0];
}

async function processRepo(repo) {
  const langBytes = await fetchLanguagesForRepo(repo);
  let languages = Object.keys(langBytes);
  let primaryLanguage = computePrimaryLanguage(langBytes) || repo.language || null;
  let finalLangBytes = langBytes;
  let metadata = undefined;

  // Apply per-repo overrides (see REPO_OVERRIDES) before saving. Useful for
  // repos where GitHub's auto-derived language stats don't represent the
  // work accurately (e.g., an archive whose stats are skewed by upstream
  // forks despite linguist-vendored attributes).
  const override = REPO_OVERRIDES[repo.full_name];
  if (override) {
    if (override.languages) languages = override.languages;
    if (override.language_bytes) finalLangBytes = override.language_bytes;
    if (override.primary_language) primaryLanguage = override.primary_language;
    if (override.metadata) metadata = override.metadata;
  }

  // Fetch portfolio documentation files
  const portfolioData = await fetchPortfolioFiles(repo);
  if (portfolioData) {
    await savePortfolioFiles(repo.name, portfolioData);
  }

  // Fetch and save preview images from .portfolio/
  const screenshots = await fetchAndSavePreviewImages(repo);

  const result = {
    repo: {
      name: repo.name,
      full_name: repo.full_name,
      html_url: repo.html_url,
      homepage: repo.homepage,
      description: repo.description,
      private: repo.private,
      fork: repo.fork,
      archived: repo.archived,
      pushed_at: repo.pushed_at
    },
    languages,
    language_bytes: finalLangBytes,
    primary_language: primaryLanguage,
    has_portfolio: !!portfolioData,
    portfolio_files: portfolioData ? Object.keys(portfolioData) : [],
    screenshots: screenshots.length > 0 ? screenshots : undefined
  };
  if (metadata) result.metadata = metadata;
  return result;
}

/**
 * Remove portfolio directories that don't correspond to any active repo or
 * manual entry. Catches stale snapshots from renamed, archived, or deleted
 * repos (e.g. `Nato-Trainer` lingering after the repo was renamed to
 * `MasterCode`). Operates on PORTFOLIO_DIR only — screenshots are pruned
 * separately because they can contain hand-curated content.
 */
function pruneOrphanPortfolioDirs(activeRepoNames) {
  if (!fs.existsSync(PORTFOLIO_DIR)) return;

  let pruned = 0;
  for (const entry of fs.readdirSync(PORTFOLIO_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (activeRepoNames.has(entry.name)) continue;

    const dirPath = path.join(PORTFOLIO_DIR, entry.name);
    fs.rmSync(dirPath, { recursive: true, force: true });
    console.log(`  Pruned orphan portfolio dir: ${entry.name}`);
    pruned++;
  }

  if (pruned === 0) {
    console.log('  No orphan portfolio dirs found.');
  } else {
    console.log(`  Pruned ${pruned} orphan portfolio dir(s).`);
  }
}

/**
 * Remove screenshot directories whose slug doesn't match any active repo
 * or manual entry. Uses the same slug function (`getRepoSlug`) the sync
 * step uses, so the active set is a direct comparison.
 */
function pruneOrphanScreenshotDirs(activeSlugs) {
  if (!fs.existsSync(SCREENSHOTS_DIR)) return;

  let pruned = 0;
  for (const entry of fs.readdirSync(SCREENSHOTS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (activeSlugs.has(entry.name)) continue;

    const dirPath = path.join(SCREENSHOTS_DIR, entry.name);
    fs.rmSync(dirPath, { recursive: true, force: true });
    console.log(`  Pruned orphan screenshot dir: ${entry.name}`);
    pruned++;
  }

  if (pruned === 0) {
    console.log('  No orphan screenshot dirs found.');
  } else {
    console.log(`  Pruned ${pruned} orphan screenshot dir(s).`);
  }
}

async function main() {
  // Fetch both private and public repos
  console.log('Fetching private repos…');
  const privateRepos = await fetchAllRepos('private');
  console.log(`Found ${privateRepos.length} private repos.`);

  console.log('Fetching public repos…');
  const publicRepos = await fetchAllRepos('public');
  console.log(`Found ${publicRepos.length} public repos.`);

  // Combine and deduplicate by name
  const allRepos = [...privateRepos];
  const privateNames = new Set(privateRepos.map(r => r.name));
  for (const repo of publicRepos) {
    if (!privateNames.has(repo.name)) {
      allRepos.push(repo);
    }
  }
  console.log(`Total unique repos: ${allRepos.length}`);

  // Ensure output directories exist
  fs.mkdirSync(PORTFOLIO_DIR, { recursive: true });
  fs.mkdirSync(SCREENSHOTS_DIR, { recursive: true });

  const enriched = [];
  let portfolioCount = 0;

  for (const repo of allRepos) {
    console.log(`Processing ${repo.name}${repo.private ? '' : ' (public)'}...`);
    const processed = await processRepo(repo);
    enriched.push(processed);
    if (processed.has_portfolio) {
      portfolioCount++;
    }
  }

  console.log(`\nFetched portfolio docs from ${portfolioCount} repos.`);

  // Add manual repos (external projects not in user's GitHub)
  for (const manualRepo of MANUAL_REPOS) {
    // Check if portfolio files exist for manual repos
    const portfolioData = {};
    for (const fileName of PORTFOLIO_FILES) {
      const filePath = path.join(PORTFOLIO_DIR, manualRepo.repo.name, fileName);
      if (fs.existsSync(filePath)) {
        portfolioData[fileName] = fs.readFileSync(filePath, 'utf8');
      }
    }

    enriched.push({
      ...manualRepo,
      has_portfolio: Object.keys(portfolioData).length > 0,
      portfolio_files: Object.keys(portfolioData)
    });
    console.log(`Added manual repo: ${manualRepo.repo.name}`);
  }

  // Build the active set of names/slugs, then prune stale directories.
  // Portfolio pruning is strict: a dir is kept only if its repo had portfolio
  // content this run (so dirs for repos that removed `.portfolio/` also get
  // cleaned). Screenshot pruning is lax: any known repo's slug is kept, since
  // screenshots can be hand-curated. Manual repos are kept unconditionally.
  const activePortfolioNames = new Set();
  const activeSlugs = new Set();
  for (const e of enriched) {
    if (e.has_portfolio) activePortfolioNames.add(e.repo.name);
    activeSlugs.add(getRepoSlug(e.repo.name));
  }
  for (const m of MANUAL_REPOS) {
    activePortfolioNames.add(m.repo.name);
    activeSlugs.add(getRepoSlug(m.repo.name));
  }

  console.log('\nPruning orphan directories...');
  pruneOrphanPortfolioDirs(activePortfolioNames);
  pruneOrphanScreenshotDirs(activeSlugs);

  // Separate featured repos from all repos
  const featuredRepos = [];

  // Add featured repos in the order specified in FEATURED_REPO_NAMES
  // Also mark them as featured in the enriched list
  for (const featuredName of FEATURED_REPO_NAMES) {
    const repoIndex = enriched.findIndex(r => r.repo.name === featuredName);
    if (repoIndex !== -1) {
      // Mark as featured in the main list
      enriched[repoIndex] = {
        ...enriched[repoIndex],
        metadata: {
          ...enriched[repoIndex].metadata,
          featured: true
        }
      };
      featuredRepos.push(enriched[repoIndex]);
    } else {
      console.warn(`Featured repo "${featuredName}" not found in fetched repos`);
    }
  }

  // Ensure output directory exists
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  // Write all repos (for backward compatibility, keep the filename)
  fs.writeFileSync(PRIVATE_REPOS_PATH, JSON.stringify(enriched, null, 2), 'utf8');
  console.log(`Wrote ${enriched.length} records to ${PRIVATE_REPOS_PATH}`);

  // Write featured repos
  fs.writeFileSync(FEATURED_REPOS_PATH, JSON.stringify(featuredRepos, null, 2), 'utf8');
  console.log(`Wrote ${featuredRepos.length} featured records to ${FEATURED_REPOS_PATH}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
